duka/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    # url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'report/(?P<year>[0-9]{4})-(?P<month>[0-9]{2})-(?P<day>[0-9]{2})/$',
        views.PasswordChangeView.as_view(), name='report_details'),
]

duka/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^join/$', views.JoinFormView.as_view(), name='join'),
    url(r'^data-collectors/$', views.CollectorListView.as_view(), name='collector_list'),
    url(r'^me/$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit/$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^p/(?P<slug>[\w\-]+)$', views.CollectorDetailView.as_view(), name='collector_detail'),
    url(r'^p/(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
            name='show'),
    url(r'^doc/$', views.DocumentCreateView.as_view(), name='home'),
    url(r'^pdoc/$', views.PrivateDocumentCreateView.as_view(), name='profile'),
]

duka/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'', include('duka.accounts.urls', namespace='accounts')),
    url(r'users/', include('duka.profiles.urls', namespace='profiles')),
    url(r'the-favorites/', include('duka.favorites.urls', namespace='favorites')),
    url(r'api/', include('duka.favorites.api.urls', namespace='api')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^aws/', include('duka.files.urls', namespace='files')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

duka/profiles/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from geoposition.fields import GeopositionField
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

from duka.storage_backends import PrivateMediaStorage


class Document(models.Model):
    uploaded_at = models.DateTimeField(auto_now_add=True)
    upload = models.FileField()


class PrivateDocument(models.Model):
    uploaded_at = models.DateTimeField(auto_now_add=True)
    upload = models.FileField(storage=PrivateMediaStorage())
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='documents')

class Location(models.Model):
    name = models.CharField(max_length=50, unique=True)
    position = GeopositionField()
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("academics:timetable-item", kwargs={"slug": self.name})


class Collector(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, primary_key=True)
    picture = models.ImageField('Profile picture',
                                upload_to='profile_pics/%Y-%m-%d/',
                                null=True,
                                blank=True)
    collector_no = models.CharField(max_length=20, unique=True, null=True, blank=True)
    id_no = models.IntegerField(null=True, blank=True, unique=True)
    dob = models.DateField(null=True, blank=True)
    MALE = 'M'
    FEMALE = 'F'
    GENDER_CHOICES = (('m', MALE), ('f', FEMALE))
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, null=True, blank=True)
    phone = models.CharField(max_length=20, null=True, blank=True)
    centre = models.ForeignKey(Location, null=True, blank=True)
    slug = models.SlugField(unique=True, editable=False)

    class Meta:
        verbose_name= 'Data Collector'
        verbose_name_plural = 'Data Collectors'

    def create_slug(instance, x=2, new_slug=None, ):
        slug = slugify(instance.collector_no)
        if new_slug is not None:
            slug = new_slug
        qs = Collector.objects.filter(slug=slug).order_by('-id')
        exists = qs.exists()
        if exists:
            slug = '%s-%s' % (slugify(instance.collector_no), x)
            x += 1
            return Collector.create_slug(instance, x=x, new_slug=slug)
        return slug

    def save(self, *args, **kwargs):
        if not self.pk:
            self.slug = Collector.create_slug(self)
            super(Collector, self).save(*args, **kwargs)
        if not self.slug:
            self.slug = Collector.create_slug(self)
        super(Collector, self).save(*args, **kwargs)

    def __str__(self):
        return ('Collector %s (%s)' % (self.user.name, self.user.email))


    def get_absolute_url(self):
        return reverse("profiles:collector_detail", kwargs={"slug": self.slug})

duka/profiles/forms.py
from __future__ import unicode_literals
from authtools import forms as authtoolsforms
from django import forms
from django.contrib.auth import get_user_model
from .models import Collector

User = get_user_model()

class JoinForm(forms.Form):
    email = forms.EmailField()
    name = forms.CharField(max_length=120)

class CollectorCreateForm(authtoolsforms.UserCreationForm):
    pass

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['name']


class CollectorForm(forms.ModelForm):
    class Meta:
        model = Collector
        fields = ('collector_no', 'phone', 'id_no', 'centre', 'gender')

duka/profiles/views.py
from __future__ import unicode_literals
from django.views import generic
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from . import forms
from . import models
from . models import Collector
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from .mixins import AjaxFormMixin
User = get_user_model()


from .models import Document, PrivateDocument

class JoinFormView(AjaxFormMixin, generic.FormView):
    form_class = forms.JoinForm
    template_name = 'profiles/ajax_form.html'
    success_url = '/'


class DocumentCreateView(CreateView):
    model = Document
    fields = ['upload', ]
    success_url = reverse_lazy('home')

    def get_context_data(self, **kwargs):
        context = super(DocumentCreateView, self).get_context_data(**kwargs)
        documents = Document.objects.all()
        context['documents'] = documents
        return context


@method_decorator(login_required, name='dispatch')
class PrivateDocumentCreateView(CreateView):
    model = PrivateDocument
    fields = ['upload', ]
    success_url = reverse_lazy('profile')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super(PrivateDocumentCreateView, self).form_valid(form)


class CollectorDetailView(generic.DetailView):
    model = Collector

class CollectorListView(generic.ListView):
    model = Collector

class ShowProfile(LoginRequiredMixin, generic.TemplateView):
    template_name = "profiles/show_profile.html"
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        slug = self.kwargs.get('slug')
        if slug:
            profile = get_object_or_404(models.Collector, slug=slug)
            user = profile.user
        else:
            user = self.request.user

        if user == self.request.user:
            kwargs["editable"] = True
        kwargs["show_user"] = user
        return super(ShowProfile, self).get(request, *args, **kwargs)


class EditProfile(LoginRequiredMixin, generic.TemplateView):
    template_name = "profiles/edit_profile.html"
    http_method_names = ['get', 'post']

    def get(self, request, *args, **kwargs):
        user = self.request.user
        if "user_form" not in kwargs:
            kwargs["user_form"] = forms.UserForm(instance=user)
        if "profile_form" not in kwargs:
            kwargs["profile_form"] = forms.CollectorForm(instance=user.collector)
        return super(EditProfile, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        user = self.request.user
        user_form = forms.UserForm(request.POST, instance=user)
        profile_form = forms.CollectorForm(request.POST,
                                         request.FILES,
                                         instance=user.collector)
        if not (user_form.is_valid() and profile_form.is_valid()):
            messages.error(request, "There was a problem with the form. "
                           "Please check the details.")
            user_form = forms.UserForm(instance=user)
            profile_form = forms.CollectorForm(instance=user.profile)
            return super(EditProfile, self).get(request,
                                                user_form=user_form,
                                                profile_form=profile_form)
        # Both forms are fine. Time to save!
        user_form.save()
        profile = profile_form.save(commit=False)
        profile.user = user
        profile.save()
        messages.success(request, "Profile details saved!")
        return redirect("profiles:show_self")

duka/profiles/templates/profiles/ajax_form.html
{% extends 'base.html' %}
{% block content %}
<h1>Join Us:</h1>
    <div class="col-sm-6 col-sm-offset-3">
    <form class="my-ajax-form" data-url="{{ request.build_absolute_uri|safe }}" action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
        <input type="submit" class="btn btn-default" value="Submit">
    </form>
    </div>
{% endblock %}
{% block scripts %}
    <script>
    $(document).ready(function () {
        var $myForm = $('.my-ajax-form')
        $myForm.submit(function (event) {
            event.preventDefault()
            var $formData = $(this).serialize()
            var $thisURL = $myForm.attr('data-url') || window.location.href
            $.ajax({
                method: 'POST',
                url: $thisURL,
                data: $formData,
                success: handleFormSuccess,
                error: handleFormError,
            })
        })

        function handleFormSuccess(data, textStatus, jqXHR) {
            console.log(data)
            console.log(textStatus)
            console.log(jqXHR)
            $myForm.reset();
        }
        function handleFormError(jqXHR, textStatus, errorThrown) {
            console.log(jqXHR)
            console.log(textStatus)
            console.log(errorThrown)
        }
    })
    </script>
{% endblock scripts %}

duka/profiles/templates/profiles/collector_detail.html
{% extends 'base.html' %}

{% block content %}
    <h2>{{ collector|upper }}</h2>
    {% if collector.picture %}
        <img src="{{ collector.picture.url }}" alt="Profile Picture" class="img img-circle" style="height: 100px">
    {% endif %}
    <br>
    <b>Name: </b> {{ collector.user.name|upper }} <br>
    <b>Centre: </b> {{ collector.centre }} <br>
    <b>Collector No: </b> {{ collector.collector_no }} <br>
    <b>ID NO: </b> {{ collector.id_no }} <br>
    <b>Gender: </b> {{ collector.gender }} <br>
    <b>Phone: </b> {{ collector.phone }}
{% endblock %}

duka/profiles/templates/profiles/collector_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}


{% block content %}
   <h1>Create a Data Collector</h1>
    <form enctype="multipart/form-data" method="post">
{#    {{ form|crispy }}#}
	{% crispy form %}
{#	{% crispy profile_form %}#}
      </form>
{% endblock %}

duka/profiles/templates/profiles/collector_list.html
{% extends 'base.html' %}

{% block content %}
    {% if collector_list %}
    <table border="1px">
        <th>No</th><th>Collector No:</th><th>User</th><th>ID NO</th><th>Centre</th>
    {% for collector in collector_list %}
       <tr><td>{{ forloop.counter }}</td><td><a href="{{ collector.get_absolute_url }}">{{ collector.collector_no }}</a>
        </td><td>{{ collector.user.name}}</td><td>{{ collector.id_no }}</td>
           <td>{{ collector.centre }}</td></tr>
    {% endfor %}
    </table>
    {% endif %}
{% endblock %}

duka/profiles/templates/profiles/document_form.html
{% extends 'base.html' %}

{% block content %}
  <h2>Public Uploads</h2>
  <h3>Upload to Amazon S3</h3>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Uploaded at</th>
        <th>Size</th>
      </tr>
    </thead>
    <tbody>
      {% for document in documents %}
        <tr>
          <td><a href="{{ document.upload.url }}" target="_blank">{{ document.upload.name }}</a></td>
          <td>{{ document.uploaded_at }}</td>
          <td>{{ document.upload.size|filesizeformat }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="3">No data.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

duka/profiles/templates/profiles/edit_profile.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block title %}{{ block.super }}Profile{% endblock %}

<!-- Benefits of the Django application -->
{% block content %}

<div class="container">
  <h1 class="text-primary">Edit Profile</h1>
  <hr>
  <div class="row">
    <!-- left column -->
    <div class="col-md-3">
      <div class="text-center">
        <img title="profile picture" class="img-circle img-responsive" src="{% thumbnail user.collector.picture|default:'default_profile.png' 140x140 crop %}">
      </div>
    </div>
      
    <!-- edit form column -->
    <div class="col-md-9">
      <h3>Personal info</h3>
      <form enctype="multipart/form-data" method="post">
          {% csrf_token %}
	{{ user_form|crispy }}
	{{ profile_form|crispy }}
          <button type="submit" class="btn btn-warning">Submit</button>
      </form>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <a class="btn btn-default pull-right" href="{% url 'accounts:password-change' %}">Change Password</a>
    </div>
  </div>
</div>
{% endblock %}

duka/profiles/templates/profiles/privatedocument_form.html
{% extends 'base.html' %}

{% block content %}
  <h2>Private Uploads</h2>
  <h3>{{ user }}'s Profile - Upload to Amazon S3</h3>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>

  <p>The files listed below are private.</p>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Uploaded at</th>
        <th>Size</th>
      </tr>
    </thead>
    <tbody>
      {% for document in user.documents.all %}
        <tr>
          <td><a href="{{ document.upload.url }}" target="_blank">{{ document.upload.name }}</a></td>
          <td>{{ document.uploaded_at }}</td>
          <td>{{ document.upload.size|filesizeformat }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="3">No data.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

duka/profiles/templates/profiles/show_profile.html
{% extends "base.html" %}

{% load staticfiles %}
{% load thumbnail %}

{% block title %}{{ block.super }}Profile{% endblock %}

{% block content %}

<div class="container profile-head">
  <div class="row">
    <div class="col-sm-10">
      <h1>{{ show_user.get_full_name }}</h1>
      {% if editable %}
      <a href="{% url 'profiles:edit_self' %}" class="btn btn-info">Edit Profile</a>
      {% endif %}
    </div>
    <div class="col-sm-2"><img title="profile picture" class="img-circle img-responsive" src="{% thumbnail show_user.profile.picture|default:'default_profile.png' 140x140 crop %}">
    </div>
  </div>
</div>

<div class="container profile-body">
  <div class="row">
    <div class="col-sm-4">
      <ul class="list-group">
        <li class="list-group-item text-muted">Profile</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Email:</strong></span> {{ show_user.email|default:"missing" }}
	  {% if show_user.profile.email_verified %}
	    <span class="glyphicon glyphicon-ok-circle" aria-hidden="true" title="This email address has been verified"></span>
	    <span class="sr-only">Verified</span>
	  {% else %}
	    <span class="glyphicon glyphicon-warning-sign" aria-hidden="true" title="This email address is not verified"></span>
	    <span class="sr-only">Not Verified</span>
	  {% endif %}
	</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Joined</strong></span> {{ show_user.date_joined }}</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Last seen</strong></span> {{ show_user.last_login }}</li>
      </ul>
    </div>
    <div class="col-sm-8">
      <div class="panel panel-default">
        <div class="panel-heading">{{ show_user.get_full_name }}'s Profile

	</div>
        <div class="panel-body">
	  <strong>Bio</strong>: {{ show_user.profile.bio }}
	</div>
      </div>
    </div>
  </div>
</div>

{% endblock %}